server:
  servlet:
    context-path: /goGedit/api

spring:
  profiles:
    active: local
    datasource:
      url: jdbc:postgresql://localhost:5432/goGedit
      username:
      password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.batch_size: 30
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    web: info
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html